### ISSUE TITLE
[NumberGuesser] Строки

### ISSUE THREAD

**Issue by pavel-b-novikov** [sanchousic/nsudotnet#1]
Чем плоха конкатенация строк через плюсики? Исправьте, покайтесь

**Comment by sanchousic** [comment]
Каюсь, конкатенация плюсиками плоха тем, что так как объекты класса String - immutable, и в данной конкретной ситуации для конкатенации с '+' это влечет создание излишних временных объектов. Что может стать трагичным. Вместо этого я решил использовать string.Format
