### ISSUE TITLE
[NumberGuesser] Скучные обои

### ISSUE THREAD

**Issue by pavel-b-novikov** [sanchousic/nsudotnet#2]
Точнее скучные ругательства. Тупо приписывается имя пользователя вначале. Разнообразьте

**Comment by sanchousic** [comment]
Этот момент связан с предыдущем issues. Переход к string.Format позволяет делать более разнообразными ругательства. 
1. То где будет использоваться имя пользователя зависит только от того где находится элемент форматирования '{число}' а не будет прописано в конкатенации с плюсиком
2. Пользуясь этим инструментарием я в одном ругательстве задействовал число попыток
