### ISSUE TITLE
[TicTacToe] Контроллер

### ISSUE THREAD

**Issue by pavel-b-novikov** [sanchousic/nsudotnet#3]
Я правильно понимаю, что в общем и целом у вас есть View, но контроллер так по мелочи пишет в консоль, дополняя общую картину?
Ненене, уважаемый, так не пойдет. Вы или вынесите из контроллера все уведомлению View об изменениях за события, или как-то еще разбейте циклическую зависимость.

**Comment by sanchousic** [comment]
Вы правильно понимаете что клаcc View для вывода в консоль информации.
И Вы опять же правы в том, что ненормально, что нечто называемое Controller занимается этим же. Потому я внес поправки, чтобы ответственность за отображение информации в консоли была только у View.
