### ISSUE TITLE
[TicTacToe] Контроль логики

### ISSUE THREAD

**Issue by pavel-b-novikov** [sanchousic/nsudotnet#4]
Слушайте, так и кто же у вас контролирует-то процесс игры? Я вижу что немного в контроллере, немного проверок в модели, немного - в поле. 
Кто у вас за что отвечает и как должно быть?

**Comment by sanchousic** [comment]
За логику игры отвечает Model, она получает аргументы и при корректности выполняет вычисления. 
Про Controller: скорее всего я неправильно назвал класс, и его следовало бы назвать парсером или обработчиком входных данных с консоли. Он ответственен за получение строк с консоли. И когда полученная строка соответствует формату, он вызывает модель.
Если и есть повторные проверки, то сделано лишь для того, чтобы при другой реализации этого парсера, модель не ломалась.

**Comment by pavel-b-novikov** [comment]
> Он ответственен за получение строк с консоли. И когда полученная строка соответствует формату, он вызывает модель.

Это и называется контроллер

**Comment by sanchousic** [comment]
скажите что же мне еще стоит переделать

вторник, 24 мая 2016 г. пользователь Pavel Novikov написал:

**Comment by sanchousic** [comment]
простите я перепутал пртложение gmail с гитхабом в браузере телефона.

вторник, 24 мая 2016 г. пользователь Alex Menkin написал:

**Comment by pavel-b-novikov** [comment]
Ну если у вас модель активная, то она не должна использоваться во View.

**Comment by sanchousic** [comment]
Учту эти замечания. Я пересмотрел свой код еще раз и у меня view зависит от модели а модель не зависит от view. Этот момент вроде выполнен. Что еще стоит поправить (или что я недопонял)

**Comment by pavel-b-novikov** [comment]
Да, кое-что еще. Если я изменю в модели какое-либо поле в обход вашего View, то состояние View не обновится.

**Comment by sanchousic** [comment]
Хорошо. Какие я решил внести поправки чтобы устранить это.
Удобнее сделать чтобы модель вызывала view а view использовала данные модели.
Я решил сделать абстрактный класс от которого зависят как модель так и view. При этом о модели view ничего не знает, лишь знает о части данных (которые позволяет ей получить этот абстрактный класс)

**Comment by pavel-b-novikov** [comment]
И как вам это помогло решить проблему?

**Comment by sanchousic** [comment]
тем что если в модели вызывается метод Step() - совершается шаг, и внутри этого метода вызывается метод view, таким образом вызывается вьюшка и обновляется.
 если вы про зависимости то, model зависит от view, view  не зависит от модели, и они обе зависят об абстрактной модели. циклической зависимости нет.

**Comment by pavel-b-novikov** [comment]
Ладно, так тоже можно, но имейте в виду что коллеги ваше решение не поймут.
