### ISSUE TITLE
[Enigma] File.ReadAllBytes(inputName);

### ISSUE THREAD

**Issue by pavel-b-novikov** [sanchousic/nsudotnet#6]
```
var data = File.ReadAllBytes(inputName);
cryptoStream.Write(data,0,data.Length);
```
Вы серьезно? А если я bluray-фильмы шифровать собрался?

**Comment by sanchousic** [comment]
Понял ошибку. Для больших файлов такое недопустимо. Чтобы решить данную проблему я использовал метод copyTo для stream'ов (считывающая файлы из одного потока и пишущая в другой)
